apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: film-ingress

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-film-service
            port:
              number: 5000

      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-film-service
            port:
              number: 80