apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-film
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-film
  template:
    metadata:
      labels:
        app: backend-film
    spec:
      containers:
      - name: backend
        image: nihaapril/film-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: NAMA
          value: "Niha April Miani"
        - name: NIM
          value: "2402567"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-film-service
spec:
  selector:
    app: backend-film
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-film
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-film
  template:
    metadata:
      labels:
        app: frontend-film
    spec:
      containers:
      - name: frontend-ui
        image: nihaapril/film-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-film-service
spec:
  type: ClusterIP   
  selector:
    app: frontend-film
  ports:
    - port: 80
      targetPort: 80